### ISSUE TITLE
Texture warning for 'biomimicry:item/dull_cactus_spike'

### ISSUE THREAD

**Issue by Xyphenore** [WitherTM/Biomimicry#1]
**Describe the bug**

For the texture 'biomimicry:item/dull_cactus_spike' I got a warning on console.

The warning from the console:

'Texture biomimicry:item/dull_cactus_spike with size 10x10 limits mip level from 4 to 1'

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Warning is printed to console.
- Create a world.

**Additional context**
- Mod version: 0.2a for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1
- Create Slice And Dice version: 3.1.2
- Farmers Delight version: 1.2.3
- Create Sifter version: 1.7.4d-9
- Kotlin for Forge version: 4.4.0

**Comment by WitherTM** [comment]
Fixed in 0.2b

**Comment by Xyphenore** [comment]
Another warning is printed for the same texture with the version 0.2b.

Texture biomimicry:item/dull_cactus_spike with size 8x8 limits mip level from 4 to 3

**Additional context**
- Mod version: 0.2b for 1.20.1
- Forge version: 47.2.1
- Create version: 0.5.1e for 1.20.1
- Create Slice And Dice version: 3.2.0
- Farmers Delight version: 1.2.3
- Create Sifter version: 1.8.1e-22
- Kotlin for Forge version: 4.5.0
