### ISSUE TITLE
Unknown item in the recipe cactus_pulp_from_milling

### ISSUE THREAD

**Issue by Xyphenore** [WitherTM/Biomimicry#2]
**Describe the bug**

The recipe 'biomimicry:cactus_pulp_from_milling' raised an error.

The error from the console:

'Parsing error loading recipe biomimicry:cactus_pulp_from_milling
com.google.gson.JsonSyntaxException: Unknown item 'biomimicry:wet_cactus''

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Create a world.
- Erro is printed to console.

**Additional context**
- Mod version: 0.2a for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1
- Create Slice And Dice version: 3.1.2
- Farmers Delight version: 1.2.3
- Create Sifter version: 1.7.4d-9
- Kotlin for Forge version: 4.4.0

**Comment by WitherTM** [comment]
Fixed in 0.2b
