### ISSUE TITLE
Texture warning for 'biomimicry:item/cactus_spike'

### ISSUE THREAD

**Issue by Xyphenore** [WitherTM/Biomimicry#3]
**Describe the bug**

For the texture 'biomimicry:item/cactus_spike' I got a warning on console.

The warning from the console:

'Texture biomimicry:item/cactus_spike with size 10x10 limits mip level from 3 to 1'

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Warning is printed to console.
- Create a world.

**Additional context**
- Mod version: 0.2b for 1.20.1
- Forge version: 47.2.1
- Create version: 0.5.1e for 1.20.1
- Create Slice And Dice version: 3.2.0
- Farmers Delight version: 1.2.3
- Create Sifter version: 1.8.1e-22
- Kotlin for Forge version: 4.5.0

**Comment by WitherTM** [comment]
sorry, I thought I had fixed this bug last patch. the fix should be on github in a bit

**Comment by WitherTM** [comment]
fixed

**Comment by WitherTM** [comment]
that fixes didn't work :(, I'm looking into it
