### ISSUE TITLE
missing item in mod

### ISSUE THREAD

**Issue by Vadewolf** [WitherTM/Biomimicry#5]
[crash-2024-01-29_14.58.29-client.txt](https://github.com/WitherTM/Biomimicry/files/14089823/crash-2024-01-29_14.58.29-client.txt)

**Comment by FooterManDev** [comment]
`create:copper_shingles` is not a part of Biomimicry.

**Comment by Vadewolf** [comment]
then pls explain how disabling the mod and my game works but having it in and it doesnt

**Comment by FooterManDev** [comment]
Use proper grammar please.
Provide a latest.log with the mod enabled.

**Comment by Vadewolf** [comment]
the crash is posted above but all i know is when i disable biomimicry the game works so

**Comment by WitherTM** [comment]
I don't know what Biomimicry has to do with this, but what Biomimicry version are you using?

**Comment by WitherTM** [comment]
okay I found the version, but I don't see anything with Biomimicry

**Comment by WitherTM** [comment]
> the crash is posted above but all i know is when i disable biomimicry the game works so

@Vadewolf do u have a latest.log? we need that to determine possible issues, not just the crash log

**Comment by FooterManDev** [comment]
@Vadewolf You need to provide:
* Latest.log: Found at `/instance/logs/`.
* Biomimicry Mod Version: Found in your mod folder, or can be seen in your launcher.
* We need more information than "But all I know is disabling Biomimicry fixes it". Nobody can debug your issue because you have not provided proper information or context.

**Comment by WitherTM** [comment]
@Vadewolf So we found out that you have a lot more mods than just biomimicry, create, farmer's delight and ex nihilo, could you try with only those and their dependencies?

**Comment by Vadewolf** [comment]
umm i dont have ex nihilio js but all i know is i will try

**Comment by Vadewolf** [comment]
[latest.log](https://github.com/WitherTM/Biomimicry/files/14102985/latest.log)
 and the latest tho i legit looked over it myself and nothing popped out besides the copper block but all i know for sure is i removed biomimicry and it works but i add it in and it doesnt

**Comment by WitherTM** [comment]
since I don't see anything wrong related to this mod, I am going to close it. I really hope u find the problem, but I can't help you with that. Have a nice day
